In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict,cross_val_score
from sklearn import model_slection
from sklearn.model_selection import KFold

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.tree import DecisionTreeClassifier

In [16]:
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix

In [5]:
iris = load_iris()

In [6]:
X,y = iris.data,iris.target

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
np.unique(y)

array([0, 1, 2])

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=50)

In [11]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
model.predict(X_test)

array([2, 2, 2, 0, 1, 2, 0, 1, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 0, 0, 2, 1, 0,
       1, 0, 2, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 1, 1,
       2, 1, 2, 2])

In [13]:
model.predict_proba(X_test)

array([[  3.75601151e-03,   4.84344131e-01,   5.11899858e-01],
       [  4.03446573e-04,   3.47411477e-01,   6.52185077e-01],
       [  1.21358456e-03,   2.99506728e-01,   6.99279687e-01],
       [  7.96765531e-01,   2.03089216e-01,   1.45252990e-04],
       [  1.30658037e-02,   7.35449996e-01,   2.51484200e-01],
       [  2.18779682e-03,   3.14927552e-01,   6.82884651e-01],
       [  8.01276880e-01,   1.98317488e-01,   4.05632471e-04],
       [  2.72856278e-02,   6.89053278e-01,   2.83661094e-01],
       [  9.98484643e-04,   2.41611830e-01,   7.57389685e-01],
       [  7.55818414e-02,   7.54215193e-01,   1.70202966e-01],
       [  8.86885204e-01,   1.13037632e-01,   7.71636859e-05],
       [  4.94903827e-02,   7.49923089e-01,   2.00586529e-01],
       [  5.08219428e-02,   7.78316119e-01,   1.70861938e-01],
       [  1.77931747e-02,   4.09574227e-01,   5.72632598e-01],
       [  8.45292267e-01,   1.54602167e-01,   1.05565792e-04],
       [  1.15111311e-02,   7.26299825e-01,   2.6218904

In [14]:
accuracy_score(model.predict(X_test),y_test)

0.93999999999999995

In [15]:
model.coef_

array([[ 0.38701729,  1.31671052, -2.0697777 , -0.92254942],
       [ 0.35704658, -1.375785  ,  0.48156115, -1.11709478],
       [-1.49468933, -1.17083538,  2.03144896,  2.24451391]])

In [17]:
confusion_matrix(y_test,model.predict(X_test))

array([[17,  0,  0],
       [ 0, 15,  2],
       [ 0,  1, 15]])

In [20]:
model = DecisionTreeClassifier(min_samples_leaf=5)
model.fit(X_train,y_train)
accuracy_score(y_test,model.predict(X_test))

0.93999999999999995

In [21]:
confusion_matrix(y_test,model.predict(X_test))

array([[17,  0,  0],
       [ 0, 17,  0],
       [ 0,  3, 13]])

In [22]:
model.predict_proba(X_test)

array([[ 0.        ,  0.66666667,  0.33333333],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.2       ,  0.8       ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.   